# Generated by Django 4.0.2 on 2022-02-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_ass_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
